//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind_WinForm.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/NorthWind.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirimdekiMiktarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> EnAzYenidenSatisMikatariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KategoriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SonlandiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> StokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TedarikciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> YeniSatisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimdekiMiktar {
            get {
                return this.BirimdekiMiktarField;
            }
            set {
                if ((object.ReferenceEquals(this.BirimdekiMiktarField, value) != true)) {
                    this.BirimdekiMiktarField = value;
                    this.RaisePropertyChanged("BirimdekiMiktar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> EnAzYenidenSatisMikatari {
            get {
                return this.EnAzYenidenSatisMikatariField;
            }
            set {
                if ((this.EnAzYenidenSatisMikatariField.Equals(value) != true)) {
                    this.EnAzYenidenSatisMikatariField = value;
                    this.RaisePropertyChanged("EnAzYenidenSatisMikatari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KategoriID {
            get {
                return this.KategoriIDField;
            }
            set {
                if ((this.KategoriIDField.Equals(value) != true)) {
                    this.KategoriIDField = value;
                    this.RaisePropertyChanged("KategoriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sonlandi {
            get {
                return this.SonlandiField;
            }
            set {
                if ((this.SonlandiField.Equals(value) != true)) {
                    this.SonlandiField = value;
                    this.RaisePropertyChanged("Sonlandi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TedarikciID {
            get {
                return this.TedarikciIDField;
            }
            set {
                if ((this.TedarikciIDField.Equals(value) != true)) {
                    this.TedarikciIDField = value;
                    this.RaisePropertyChanged("TedarikciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> YeniSatis {
            get {
                return this.YeniSatisField;
            }
            set {
                if ((this.YeniSatisField.Equals(value) != true)) {
                    this.YeniSatisField = value;
                    this.RaisePropertyChanged("YeniSatis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IServiceOf_ProductDTO")]
    public interface IServiceOf_ProductDTO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Paging", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/PagingResponse")]
        System.Collections.Generic.List<NorthWind_WinForm.ProductServiceReference.ProductDTO> Paging();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Paging", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/PagingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind_WinForm.ProductServiceReference.ProductDTO>> PagingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Add", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/AddResponse")]
        bool Add(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Add", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/UpdateResponse")]
        bool Update(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/DeleteResponse")]
        bool Delete(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ProductDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_ProductDTO/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_ProductDTOChannel : NorthWind_WinForm.ProductServiceReference.IServiceOf_ProductDTO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_ProductDTOClient : System.ServiceModel.ClientBase<NorthWind_WinForm.ProductServiceReference.IServiceOf_ProductDTO>, NorthWind_WinForm.ProductServiceReference.IServiceOf_ProductDTO {
        
        public ServiceOf_ProductDTOClient() {
        }
        
        public ServiceOf_ProductDTOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_ProductDTOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ProductDTOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ProductDTOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<NorthWind_WinForm.ProductServiceReference.ProductDTO> Paging() {
            return base.Channel.Paging();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind_WinForm.ProductServiceReference.ProductDTO>> PagingAsync() {
            return base.Channel.PagingAsync();
        }
        
        public bool Add(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.Add(dto);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.AddAsync(dto);
        }
        
        public bool Update(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.Update(dto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.UpdateAsync(dto);
        }
        
        public bool Delete(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.Delete(dto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(NorthWind_WinForm.ProductServiceReference.ProductDTO dto) {
            return base.Channel.DeleteAsync(dto);
        }
    }
}
